### ISSUE TITLE
Multiple instances on opening projects

### ISSUE THREAD

**Issue by vanita5** [krasa/CpuUsageIndicator#1]
After opening another project inside of the IDE, you will have two indicators in the statusbar. Opening the next project adds another indicator to the statusbar and so on...

**Reproduce:**
1. Open the IDE (In my case PHP Storm 2016.2.1)
2. If no project is opened automatically, open a project
3. Go to *File -> Open* and choose another project **in the same window**.

**=>** You will now have two CPU usage indicators

**Possible fix:**

Inside your class `CpuUsageProjectComponent` you probably have to implement `projectClosed()` and remove the widget from the statusbar.

**Comment by krasa** [comment]
Thanks! I always open a project in a new window.
